# This configuration file specifies the environment and model parameters.
# Please note the following:
# 1. To use the DMC benchmarks, use the following setting: use_gym_env_with_replay_buffer: False
# This ensures that the original dataset structure from Dreamer us used. 
# Do not set the flag to true, otherwise, the code will not run.
# ------
# 2. To use irregular setting:
# - Edit parameters of the gym_pendulum config
# - Run the script with --config gym_Pendulum
# - Enable new replay buffer: -- use_gym_env_with_replay_buffer: True
# - Specify number of action holds by action_hold_min and action_hold_max
# - Specify frequency of environment
# - Enable subsampling with the flag subsampling
# - Run only one environment and no parallel environments since this case was not tested
# Note: The irregular setting was not tested on other gym environments. Therefore, the code may crash.
# ------
# 3. To switch between the RSSM and latent neural SDE model, use the flag use_sde

defaults:
  use_gym_env_with_replay_buffer: False
  use_sde: True

  logdir: null
  traindir: null
  evaldir: null
  offline_traindir: ''
  offline_evaldir: ''
  seed: 0
  deterministic_run: False
  steps: 1e6
  parallel: False
  eval_every: 1e4
  eval_episode_num: 10
  log_every: 1e4
  reset_every: 0
  device: 'cuda:0'
  compile: True
  precision: 32
  debug: False
  video_pred_log: True
  sde_solver: 'euler'

  # Environment
  task: 'dmc_walker_walk'
  size: [64, 64]
  envs: 1
  action_repeat: 2
  time_limit: 1000
  grayscale: False
  prefill: 2500
  reward_EMA: True

  # Model
  dyn_hidden: 512
  dyn_deter: 512
  dyn_stoch: 32
  dt: 1.0
  imagination_dt: 0.125
  imagination_time: 1.0
  dyn_discrete: False
  dyn_rec_depth: 1
  dyn_mean_act: 'none'
  dyn_std_act: 'sigmoid2'
  dyn_min_std: 0.1
  grad_heads: ['decoder', 'reward', 'cont']
  units: 512
  act: 'SiLU'
  norm: True
  encoder:
    {mlp_keys: '$^', cnn_keys: 'image', act: 'SiLU', norm: True, cnn_depth: 32, kernel_size: 4, minres: 4, mlp_layers: 5, mlp_units: 1024, symlog_inputs: True}
  decoder:
    {mlp_keys: '$^', cnn_keys: 'image', act: 'SiLU', norm: True, cnn_depth: 32, kernel_size: 4, minres: 4, mlp_layers: 5, mlp_units: 1024, cnn_sigmoid: False, image_dist: mse, vector_dist: normal, outscale: 1.0}
  actor:
    {layers: 2, dist: 'normal', entropy: 3e-4, unimix_ratio: 0.01, std: 'learned', min_std: 0.1, max_std: 1.0, temp: 0.1, lr: 3e-5, eps: 1e-5, grad_clip: 100.0, outscale: 1.0}
  critic:
    {layers: 2, dist: 'symlog_disc', slow_target: True, slow_target_update: 1, slow_target_fraction: 0.02, lr: 3e-5, eps: 1e-5, grad_clip: 100.0, outscale: 0.0}
  reward_head:
    {layers: 2, dist: 'symlog_disc', loss_scale: 1.0, outscale: 0.0}
  cont_head:
    {layers: 2, loss_scale: 1.0, outscale: 1.0}
  dyn_scale: 0.5
  rep_scale: 0.1
  kl_free: 1.0
  weight_decay: 0.0
  unimix_ratio: 0.01
  initial: 'learned'

  # Training
  batch_size: 16
  batch_length: 64
  train_ratio: 512
  pretrain: 100
  model_lr: 1e-4
  opt_eps: 1e-8
  grad_clip: 1000
  dataset_size: 1000000
  opt: 'adam'

  # Behavior.
  discount: 0.997
  discount_lambda: 0.95
  imag_horizon: 15
  imag_gradient: 'dynamics'
  imag_gradient_mix: 0.0
  eval_state_mean: False

  # Exploration
  expl_behavior: 'greedy'
  expl_until: 0
  expl_extr_scale: 0.0
  expl_intr_scale: 1.0
  disag_target: 'stoch'
  disag_log: True
  disag_models: 10
  disag_offset: 1
  disag_layers: 4
  disag_units: 400
  disag_action_cond: False

dmc_proprio:
  steps: 5e5
  action_repeat: 2
  envs: 4
  train_ratio: 512
  video_pred_log: false
  encoder: {mlp_keys: '.*', cnn_keys: '$^'}
  decoder: {mlp_keys: '.*', cnn_keys: '$^'}

dmc_vision:
  steps: 1e6
  action_repeat: 2
  envs: 4
  train_ratio: 512
  video_pred_log: true
  encoder: {mlp_keys: '$^', cnn_keys: 'image'}
  decoder: {mlp_keys: '$^', cnn_keys: 'image'}

crafter:
  task: crafter_reward
  step: 1e6
  action_repeat: 1
  envs: 1
  train_ratio: 512
  video_pred_log: true
  dyn_hidden: 1024
  dyn_deter: 4096
  units: 1024
  encoder: {mlp_keys: '$^', cnn_keys: 'image', cnn_depth: 96, mlp_layers: 5, mlp_units: 1024}
  decoder: {mlp_keys: '$^', cnn_keys: 'image', cnn_depth: 96, mlp_layers: 5, mlp_units: 1024}
  actor: {layers: 5, dist: 'onehot', std: 'none'}
  value: {layers: 5}
  reward_head: {layers: 5}
  cont_head: {layers: 5}
  imag_gradient: 'reinforce'

atari100k:
  steps: 4e5
  envs: 1
  action_repeat: 4
  train_ratio: 1024
  video_pred_log: true
  eval_episode_num: 100
  actor: {dist: 'onehot', std: 'none'}
  imag_gradient: 'reinforce'
  stickey: False
  lives: unused
  noops: 30
  resize: opencv
  actions: needed
  time_limit: 108000

minecraft:
  task: minecraft_diamond
  step: 1e8
  parallel: True
  envs: 16
  # no eval
  eval_episode_num: 0
  eval_every: 1e4
  action_repeat: 1
  train_ratio: 16
  video_pred_log: true
  dyn_hidden: 1024
  dyn_deter: 4096
  units: 1024
  encoder: {mlp_keys: 'inventory|inventory_max|equipped|health|hunger|breath|obs_reward', cnn_keys: 'image', cnn_depth: 96, mlp_layers: 5, mlp_units: 1024}
  decoder: {mlp_keys: 'inventory|inventory_max|equipped|health|hunger|breath', cnn_keys: 'image', cnn_depth: 96, mlp_layers: 5, mlp_units: 1024}
  actor: {layers: 5, dist: 'onehot', std: 'none'}
  value: {layers: 5}
  reward_head: {layers: 5}
  cont_head: {layers: 5}
  imag_gradient: 'reinforce'
  break_speed: 100.0
  time_limit: 36000

memorymaze:
  steps: 1e8
  action_repeat: 2
  actor: {dist: 'onehot', std: 'none'}
  imag_gradient: 'reinforce'
  task: 'memorymaze_9x9'

debug:
  debug: True
  pretrain: 1
  prefill: 1
  batch_size: 10
  batch_length: 20

gym_pendulum:
  use_sde: True     
  # If new replay buffer is used, set flag to true.
  use_gym_env_with_replay_buffer: True  
  seed: 200
  
  steps: 50000
  envs: 1
  action_repeat: 1
  train_ratio: 160
  video_pred_log: True
  capacity: 100
  prefill: 5000
  log_every: 1000
  eval_every: 1000

  task: gym_Pendulum-v1

  encoder:
    mlp_keys: 'obs'
    cnn_keys: '$^'
    act: 'SiLU'
    norm: True
    cnn_depth: 32
    kernel_size: 4
    minres: 4
    mlp_layers: 2
    mlp_units: 32
    symlog_inputs: True  

  decoder:
    mlp_keys: 'obs'
    cnn_keys: '$^'
    act: 'SiLU'
    norm: True
    cnn_depth: 32
    kernel_size: 4
    minres: 4
    mlp_layers: 2
    mlp_units: 128
    cnn_sigmoid: False
    image_dist: normal
    vector_dist: symlog_mse  
    outscale: 1.0

  # Model parameters
  dyn_stoch: 16
  dyn_deter: 16
  dyn_discrete: False 
  model_lr: 5e-4
  grad_clip: 10.0  
  kl_free: 1.0        
  dyn_scale: 1.0        
  rep_scale: 0.1            
  
  # Frequency of environment in training mode
  dt_env_train: 0.1
  # Time limit for one episode in seconds in training mode
  time_limit_train: 10
  # Frequency of environment in evaluation mode
  dt_env_eval: 0.01
  # Time limit for one episode in seconds in evaluation mode
  time_limit_eval: 10

  # Solver dt for for world model training
  dt_wm: 0.1
  # Sequence time for world model training (Time grid for WM training: [0, dt_wm, 2*dt_wm, ..., sequence_time]). Used when new replay buffer is used 
  sequence_time: 2.0

  # Solver dt for imagination
  dt_planning: 0.1

  # Time duration of one imagination step 
  imagination_time: 0.1

  # Imagination horizon defines the number of imagination steps 
  # (Time grid for imagination: [0, imagination_time, 2*imagination_time, ..., imag_horizon*imagination_time])
  imag_horizon: 15

  # Batch length is used as sequence length when original data set is used
  batch_length: 20    

  # Settings for irregular case
  # Enable/Disable irregularity 
  irregular: False
  # Minimum action hold
  action_hold_min: 1
  # Maximum action hold
  action_hold_max: 2
  # Enable/Disable Subsampling
  subsampling_enabled: False
